# Generated by Django 4.1.7 on 2023-03-02 09:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=50)),
                ('author_bdate', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=100)),
                ('book_page', models.IntegerField()),
                ('book_rating', models.IntegerField()),
                ('book_desc', models.TextField(blank=True, default='Description not found...')),
                ('book_rdate', models.CharField(max_length=10)),
                ('book_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.author')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cate_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cate_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('gender_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gender_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Holds',
            fields=[
                ('hold_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hold_books', models.ManyToManyField(blank=True, to='api.books')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('publisher_name', models.CharField(max_length=50)),
                ('publisher_fdate', models.CharField(max_length=10)),
                ('publisher_adress', models.TextField(blank=True, default='Blank adress')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_name', models.CharField(max_length=50)),
                ('member_jdate', models.DateTimeField(auto_now_add=True)),
                ('member_bdate', models.DateTimeField()),
                ('member_borrowedbooks', models.ManyToManyField(blank=True, to='api.books')),
                ('member_gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gender')),
                ('member_holds', models.ManyToManyField(blank=True, to='api.holds')),
            ],
        ),
        migrations.AddField(
            model_name='holds',
            name='hold_holder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.member'),
        ),
        migrations.AddField(
            model_name='books',
            name='book_category',
            field=models.ManyToManyField(to='api.category'),
        ),
        migrations.AddField(
            model_name='books',
            name='book_publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.publisher'),
        ),
    ]
