# Generated by Django 4.1.7 on 2023-03-02 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='member_holds',
        ),
        migrations.AddField(
            model_name='member',
            name='member_holds',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.holds'),
        ),
    ]
