# Generated by Django 4.1.7 on 2023-03-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_member_member_holds_member_member_holds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holds',
            name='hold_holder',
            field=models.CharField(max_length=50),
        ),
    ]
