# Generated by Django 4.1.7 on 2023-03-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_holds_hold_holder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_bdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_jdate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
